# Generated by Django 5.0.6 on 2024-07-28 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appseguros', '0003_siniestro_tarea'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siniestro',
            old_name='numero_sinietro',
            new_name='numero_siniestro',
        ),
    ]
