# Generated by Django 5.0.6 on 2024-07-30 15:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appseguros', '0004_rename_numero_sinietro_siniestro_numero_siniestro'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
