# Generated by Django 5.0.6 on 2024-07-31 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appseguros', '0008_rename_año_vehiculo_anio_asegurado_mail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asegurado',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='asegurado',
            name='telefono',
        ),
        migrations.AlterField(
            model_name='siniestro',
            name='asegurado',
            field=models.CharField(max_length=30),
        ),
    ]
