# Generated by Django 5.0.6 on 2024-07-31 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appseguros', '0009_remove_asegurado_mail_remove_asegurado_telefono_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asegurado',
            name='mail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='asegurado',
            name='telefono',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='siniestro',
            name='asegurado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appseguros.asegurado'),
        ),
        migrations.CreateModel(
            name='ComentarioSiniestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=2000)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('siniestro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='appseguros.siniestro')),
            ],
        ),
    ]
