# Generated by Django 5.0.6 on 2024-07-31 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appseguros', '0012_compania_remove_vehiculo_numero_motor_vehiculo_marca_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poliza',
            name='estado_poliza',
            field=models.CharField(choices=[('vigente', 'Vigente'), ('anulada', 'Anulada'), ('vencida', 'Vencida')], default='vigente', max_length=20),
        ),
    ]
