# Generated by Django 5.0.6 on 2024-08-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appseguros', '0013_alter_poliza_estado_poliza'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='tipo',
            field=models.CharField(choices=[('auto', 'Auto'), ('moto', 'Moto'), ('camion', 'Camión')], default='auto', max_length=10),
        ),
    ]
