# Generated by Django 5.0.6 on 2024-08-01 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appseguros', '0014_vehiculo_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poliza',
            name='tipo_seguro',
            field=models.CharField(choices=[('moto', 'Moto'), ('auto', 'Auto'), ('bici', 'Bicicleta'), ('camion', 'Camión'), ('combinado_familiar', 'Combinado Familiar'), ('otros', 'Otros')], max_length=20),
        ),
    ]
