# Generated by Django 5.0.6 on 2024-08-01 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appseguros', '0015_alter_poliza_tipo_seguro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poliza',
            name='es_vehiculo',
        ),
    ]
