# Generated by Django 5.0.6 on 2024-08-01 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appseguros', '0016_remove_poliza_es_vehiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='estado',
            field=models.CharField(choices=[('activa', 'Activa'), ('terminada', 'Terminada')], default='activa', max_length=10),
        ),
    ]
