# Generated by Django 5.0.6 on 2024-08-02 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appseguros', '0017_tarea_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='siniestro',
            name='estado',
            field=models.CharField(choices=[('activa', 'Activa'), ('terminada', 'Terminada')], default='activa', max_length=10),
        ),
    ]
