# Generated by Django 5.0.6 on 2024-08-02 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appseguros', '0019_alter_tarea_subtitulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='subtitulo',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
