# Generated by Django 5.0.6 on 2024-08-07 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inspeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asegurado', models.CharField(max_length=100)),
                ('dominio', models.CharField(max_length=100)),
                ('foto_frente', models.URLField(blank=True, null=True)),
                ('foto_trasera', models.URLField(blank=True, null=True)),
                ('foto_lateral_derecho', models.URLField(blank=True, null=True)),
                ('foto_lateral_izquierdo', models.URLField(blank=True, null=True)),
                ('dni_frente', models.URLField(blank=True, null=True)),
                ('dni_dorso', models.URLField(blank=True, null=True)),
                ('cedula_verde_frente', models.URLField(blank=True, null=True)),
                ('cedula_verde_dorso', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
