# Generated by Django 5.0.6 on 2024-08-07 15:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecciones', '0002_inspeccion_enlace_unico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspeccion',
            name='enlace_unico',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
